### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6

### ISSUE THREAD

**Issue by panthony** [NLincoln/ember-paper-dual-slider#3]
Hello,

Just opening an issue because I have this deprecation warning for quite a while now.

Wondering if you planned to fix it at some point or if you do not maintain this addon anymore

**Comment by cursedquail** [comment]
I don't really maintain this add-on, but for small issues like this I'll do an update. 

If you want to PR I can hit the merge button soon and then release sometime around 8pm tonight? (cst)

Also sorry about the delay I've been on vacation.

**Comment by panthony** [comment]
Ok thanks, not sure I'll be able to do it in time but I'll eventually provide a PR, this is not blocker at all.

I'll probably bump babel, remove usage of `sendAction` and of global `Ember`, this way this addon should be compliant with the future ember updates.

**Comment by cursedquail** [comment]
All the issues in the above comment have been fixed as of `0.3.0`. This is probably a breaking change due to node version requirements changing, so be aware of that.
